### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by p1nkyy** [RedirectCleaner/RedirectCleaner#1]
Hello, I missed this add-on so much. Was sad when it suddenly didn't work then disappear from AMO. Thanks for resurrecting it! My question is, how to install this? Didn't see any .xpi in this repo that I can download & install.

**Comment by RedirectCleaner** [comment]
From here https://addons.mozilla.org/en-us/firefox/addon/redirectcleaner/

**Comment by p1nkyy** [comment]
Thanks. You are awesome!
